"""unique reaction per user per post

Revision ID: 4579f8386ec1
Revises: 3823eb24b8d9
Create Date: 2026-06-27 02:28:08.232936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4579f8386ec1'
down_revision: Union[str, Sequence[str], None] = '3823eb24b8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_reaction_per_user_per_post', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_reaction_per_user_per_post', type_='unique')
    # ### end Alembic commands ###

