
"""add phone dob gender otp fields to user

Revision ID: d89be35abe9f
Revises: 4579f8386ec1
Create Date: 2026-07-11 19:13:44.390246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89be35abe9f'
down_revision: Union[str, Sequence[str], None] = '4579f8386ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='genderenum'), nullable=True))
        batch_op.add_column(sa.Column('email_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.drop_column('email_otp_expires_at')
        batch_op.drop_column('email_otp')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone_number')
    # ### end Alembic commands ###

